#!/bin/bash

set -euo pipefail

OUTPUT_PATH="${DOCS_OUTPUT_PATH:-.build/docc-site/WidgetGuideView}"
HOSTING_BASE_PATH="${HOSTING_BASE_PATH:-${DOCS_HOSTING_BASE_PATH:-WidgetGuideView}}"
IOS_SIMULATOR_SDK="${IOS_SIMULATOR_SDK:-$(xcrun --sdk iphonesimulator --show-sdk-path)}"
IOS_SIMULATOR_TARGET="${IOS_SIMULATOR_TARGET:-$(uname -m)-apple-ios13.0-simulator}"

rm -rf "$OUTPUT_PATH"
mkdir -p "$(dirname "$OUTPUT_PATH")"

swift package \
  --sdk "$IOS_SIMULATOR_SDK" \
  --triple "$IOS_SIMULATOR_TARGET" \
  --allow-writing-to-directory "$OUTPUT_PATH" \
  generate-documentation \
  --target WidgetGuideView \
  --disable-indexing \
  --output-path "$OUTPUT_PATH" \
  --transform-for-static-hosting \
  --hosting-base-path "$HOSTING_BASE_PATH"

HOSTING_BASE_PATH="/${HOSTING_BASE_PATH#/}"
export HOSTING_BASE_PATH
perl -0pi -e '
  my $base = $ENV{"HOSTING_BASE_PATH"};
  s#href="/favicon\.ico"#href="$base/favicon.ico"#g;
  s#href="/favicon\.svg"#href="$base/favicon.svg"#g;
  s#var baseUrl = "/"#var baseUrl = "$base/"#g;
  s#src="/js/#src="$base/js/#g;
  s#href="/css/#href="$base/css/#g;
' "$OUTPUT_PATH/index.html"

rm -rf ./docs
rm -rf ./WidgetGuideView.doccarchive

